require: rubocop-rspec

Metrics/LineLength:
  Max: 95
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'Gemfile'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/cucumber.rake'
Rails/DynamicFindBy:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - 'spec/integration/**/*'
RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
RSpec/NestedGroups:
  Exclude:
    - 'spec/**/*'
RSpec/NamedSubject:
  Exclude:
    - 'spec/**/*'
RSpec/LeadingSubject:
  Exclude:
    - 'spec/**/*'
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/**/*'
RSpec/MessageSpies:
  Enabled: false

# Rails exceptions
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
